import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const ROOT = resolve(__dirname, "..");

const GEMINI_PROCESSING_FILES = [
  "../../packages/backend/convex/processing/gemini.ts",
  "../../packages/backend/convex/processing/embeddings.ts",
  "../../packages/backend/convex/processing/handlers.ts",
  "../../packages/backend/convex/processing/pipeline.ts",
  "../../packages/backend/convex/processing/runs.ts",
  "../../packages/backend/convex/search/actions.ts",
  "../../packages/backend/convex/search/queries.ts",
];

const GEMINI_EMBEDDING_WRITER_FILES = [
  "../../packages/backend/convex/processing/handlers.ts",
  "../../packages/backend/convex/migration/reembed_helpers.ts",
];

function readProjectFile(relativePath: string) {
  return readFileSync(resolve(ROOT, relativePath), "utf8");
}

describe("AI model migration", () => {
  it("uses the active Gemini generation and embedding defaults", () => {
    const gemini = readProjectFile("../../packages/backend/convex/processing/gemini.ts");
    const embeddings = readProjectFile("../../packages/backend/convex/processing/embeddings.ts");

    expect(gemini).toContain('cheap: "gemini-3.1-flash-lite"');
    expect(gemini).toContain('normal: "gemini-3.1-pro-preview"');
    expect(gemini).toContain('embedding: "gemini-embedding-2"');
    expect(embeddings).toContain('EMBEDDING_MODEL = "gemini-embedding-2"');
    expect(embeddings).toContain('EMBEDDING_MODEL_KEY = "gemini-embedding-2:1536"');
  });

  it("keeps bookmark processing and search off OpenAI generation and embedding models", () => {
    const offenders = GEMINI_PROCESSING_FILES.flatMap((relativePath) => {
      const content = readProjectFile(relativePath);
      const forbiddenPatterns = [
        "OPENAI_MODELS.cheap",
        "OPENAI_MODELS.embedding",
        "text-embedding-3-small",
      ];

      return forbiddenPatterns
        .filter((pattern) => content.includes(pattern))
        .map((pattern) => `${relativePath}: ${pattern}`);
    });

    expect(offenders).toEqual([]);
  });

  it("marks newly stored bookmark vectors with the active Gemini embedding model", () => {
    const offenders = GEMINI_EMBEDDING_WRITER_FILES.filter((relativePath) => {
      const content = readProjectFile(relativePath);

      return !content.includes("EMBEDDING_MODEL_KEY") &&
        !content.includes("CURRENT_EMBEDDING_MODEL_KEY");
    });

    expect(offenders).toEqual([]);
  });

  it("does not search or reuse vectors unless they were generated by the active Gemini embedding model", () => {
    const searchAndReuseFiles = [
      "../../packages/backend/convex/search/actions.ts",
      "../../packages/backend/convex/processing/runs.ts",
    ];

    const offenders = searchAndReuseFiles.filter((relativePath) => {
      const content = readProjectFile(relativePath);

      return !content.includes("EMBEDDING_MODEL_KEY") ||
        !content.includes("embeddingModel");
    });

    expect(offenders).toEqual([]);
  });
});
