import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const ROOT = resolve(__dirname, "..");

const GEMINI_PROCESSING_FILES = [
  "src/lib/inngest/process-bookmark.utils.ts",
  "src/lib/inngest/bookmark-type/process-article-bookmark.ts",
  "src/lib/inngest/bookmark-type/process-image-bookmark.ts",
  "src/lib/inngest/bookmark-type/process-page-bookmark.ts",
  "src/lib/inngest/bookmark-type/process-pdf-bookmark.ts",
  "src/lib/inngest/bookmark-type/process-product-bookmark.ts",
  "src/lib/inngest/bookmark-type/process-tweet-bookmark.ts",
  "src/lib/inngest/bookmark-type/process-youtube-bookmark.ts",
  "src/lib/search/optimized-search.ts",
  "src/lib/search/search-by-query.ts",
  "src/lib/search/embedding-cache.ts",
];

const GEMINI_EMBEDDING_WRITER_FILES = [
  "src/lib/inngest/bookmark-type/process-article-bookmark.ts",
  "src/lib/inngest/bookmark-type/process-image-bookmark.ts",
  "src/lib/inngest/bookmark-type/process-page-bookmark.ts",
  "src/lib/inngest/bookmark-type/process-pdf-bookmark.ts",
  "src/lib/inngest/bookmark-type/process-product-bookmark.ts",
  "src/lib/inngest/bookmark-type/process-tweet-bookmark.ts",
  "src/lib/inngest/bookmark-type/process-youtube-bookmark.ts",
];

function readProjectFile(relativePath: string) {
  return readFileSync(resolve(ROOT, relativePath), "utf8");
}

describe("AI model migration", () => {
  it("uses the active Gemini generation and embedding defaults", () => {
    const content = readProjectFile("src/lib/gemini.ts");

    expect(content).toContain('cheap: "gemini-3.1-flash-lite"');
    expect(content).toContain('normal: "gemini-3.1-pro-preview"');
    expect(content).toContain('embedding: "gemini-embedding-2"');
    expect(content).toContain("GEMINI_EMBEDDING_METADATA_VALUE");
  });

  it("keeps bookmark processing and search off OpenAI generation and embedding models", () => {
    const offenders = GEMINI_PROCESSING_FILES.flatMap((relativePath) => {
      const content = readProjectFile(relativePath);
      const forbiddenPatterns = [
        "OPENAI_MODELS.cheap",
        "OPENAI_MODELS.embedding",
        "text-embedding-3-small",
      ];

      return forbiddenPatterns
        .filter((pattern) => content.includes(pattern))
        .map((pattern) => `${relativePath}: ${pattern}`);
    });

    expect(offenders).toEqual([]);
  });

  it("marks newly stored bookmark vectors with the active Gemini embedding model", () => {
    const offenders = GEMINI_EMBEDDING_WRITER_FILES.filter((relativePath) => {
      const content = readProjectFile(relativePath);

      return !content.includes("GEMINI_EMBEDDING_METADATA_VALUE") ||
        !content.includes("jsonb_set(") ||
        !content.includes("'{embeddingModel}'");
    });

    expect(offenders).toEqual([]);
  });

  it("does not search or reuse vectors unless they were generated by the active Gemini embedding model", () => {
    const searchAndReuseFiles = [
      "src/lib/search/optimized-search.ts",
      "src/lib/search/search-by-query.ts",
      "src/lib/inngest/bookmark-reuse.utils.ts",
    ];

    const offenders = searchAndReuseFiles.filter((relativePath) => {
      const content = readProjectFile(relativePath);

      return !content.includes("GEMINI_EMBEDDING_METADATA_VALUE") ||
        !content.includes("embeddingModel");
    });

    expect(offenders).toEqual([]);
  });
});
