/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as VerifyRouteImport } from "./routes/verify";
import { Route as VariationsRouteImport } from "./routes/variations";
import { Route as UpgradeRouteImport } from "./routes/upgrade";
import { Route as ToolsRouteImport } from "./routes/tools";
import { Route as TermsRouteImport } from "./routes/terms";
import { Route as TagsRouteImport } from "./routes/tags";
import { Route as StartRouteImport } from "./routes/start";
import { Route as SigninRouteImport } from "./routes/signin";
import { Route as ProducthuntRouteImport } from "./routes/producthunt";
import { Route as PrivacyRouteImport } from "./routes/privacy";
import { Route as PricingRouteImport } from "./routes/pricing";
import { Route as PostsRouteImport } from "./routes/posts";
import { Route as IosRouteImport } from "./routes/ios";
import { Route as ImportsRouteImport } from "./routes/imports";
import { Route as HelpRouteImport } from "./routes/help";
import { Route as GoodbyeRouteImport } from "./routes/goodbye";
import { Route as ExtensionsRouteImport } from "./routes/extensions";
import { Route as ExportsRouteImport } from "./routes/exports";
import { Route as ExploreRouteImport } from "./routes/explore";
import { Route as DocsRouteImport } from "./routes/docs";
import { Route as ContactRouteImport } from "./routes/contact";
import { Route as ChangelogRouteImport } from "./routes/changelog";
import { Route as BillingRouteImport } from "./routes/billing";
import { Route as AppRouteImport } from "./routes/app";
import { Route as AdminRouteImport } from "./routes/admin";
import { Route as AccountRouteImport } from "./routes/account";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as SplatRouteImport } from "./routes/$";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as UpgradeSuccessRouteImport } from "./routes/upgrade.success";
import { Route as UpgradeNewPricingRouteImport } from "./routes/upgrade.new-pricing";
import { Route as UnsubscribeUserIdRouteImport } from "./routes/unsubscribe.$userId";
import { Route as USlugRouteImport } from "./routes/u.$slug";
import { Route as ToolsYoutubeMetadataRouteImport } from "./routes/tools.youtube-metadata";
import { Route as ToolsOgImagesRouteImport } from "./routes/tools.og-images";
import { Route as ToolsExtractMetadataRouteImport } from "./routes/tools.extract-metadata";
import { Route as ToolsExtractFaviconsRouteImport } from "./routes/tools.extract-favicons";
import { Route as ToolsExtractContentRouteImport } from "./routes/tools.extract-content";
import { Route as PostsSlugRouteImport } from "./routes/posts.$slug";
import { Route as PBookmarkIdRouteImport } from "./routes/p.$bookmarkId";
import { Route as LandingHeader2RouteImport } from "./routes/landing.header-2";
import { Route as LandingHeaderRouteImport } from "./routes/landing.header";
import { Route as DocsSlugRouteImport } from "./routes/docs.$slug";
import { Route as ChangelogVersionsRouteImport } from "./routes/changelog.versions";
import { Route as AuthMobileLoginRouteImport } from "./routes/auth.mobile-login";
import { Route as AppAgentsRouteImport } from "./routes/app.agents";
import { Route as ApiTagsRouteImport } from "./routes/api.tags";
import { Route as ApiBugReportRouteImport } from "./routes/api.bug-report";
import { Route as ApiBookmarksRouteImport } from "./routes/api.bookmarks";
import { Route as AdminUsersRouteImport } from "./routes/admin.users";
import { Route as AdminSendEmailRouteImport } from "./routes/admin.send-email";
import { Route as AdminConversationsRouteImport } from "./routes/admin.conversations";
import { Route as AccountPublicLinkRouteImport } from "./routes/account.public-link";
import { Route as AccountKeysRouteImport } from "./routes/account.keys";
import { Route as PBookmarkIdReadRouteImport } from "./routes/p.$bookmarkId.read";
import { Route as AppBBookmarkIdRouteImport } from "./routes/app.b.$bookmarkId";
import { Route as ApiWebhooksStripeRouteImport } from "./routes/api.webhooks.stripe";
import { Route as ApiV1SplatRouteImport } from "./routes/api.v1.$";
import { Route as ApiUserLimitsRouteImport } from "./routes/api.user.limits";
import { Route as ApiMobileCheckoutRouteImport } from "./routes/api.mobile.checkout";
import { Route as ApiInsightsSplatRouteImport } from "./routes/api.insights.$";
import { Route as ApiBookmarksBookmarkIdRouteImport } from "./routes/api.bookmarks.$bookmarkId";
import { Route as ApiAuthSplatRouteImport } from "./routes/api.auth.$";
import { Route as AdminUsersUserIdRouteImport } from "./routes/admin.users.$userId";
import { Route as AdminConversationsIdRouteImport } from "./routes/admin.conversations.$id";
import { Route as ApiBookmarksBookmarkIdUploadScreenshotRouteImport } from "./routes/api.bookmarks.$bookmarkId.upload-screenshot";

const VerifyRoute = VerifyRouteImport.update({
  id: "/verify",
  path: "/verify",
  getParentRoute: () => rootRouteImport,
} as any);
const VariationsRoute = VariationsRouteImport.update({
  id: "/variations",
  path: "/variations",
  getParentRoute: () => rootRouteImport,
} as any);
const UpgradeRoute = UpgradeRouteImport.update({
  id: "/upgrade",
  path: "/upgrade",
  getParentRoute: () => rootRouteImport,
} as any);
const ToolsRoute = ToolsRouteImport.update({
  id: "/tools",
  path: "/tools",
  getParentRoute: () => rootRouteImport,
} as any);
const TermsRoute = TermsRouteImport.update({
  id: "/terms",
  path: "/terms",
  getParentRoute: () => rootRouteImport,
} as any);
const TagsRoute = TagsRouteImport.update({
  id: "/tags",
  path: "/tags",
  getParentRoute: () => rootRouteImport,
} as any);
const StartRoute = StartRouteImport.update({
  id: "/start",
  path: "/start",
  getParentRoute: () => rootRouteImport,
} as any);
const SigninRoute = SigninRouteImport.update({
  id: "/signin",
  path: "/signin",
  getParentRoute: () => rootRouteImport,
} as any);
const ProducthuntRoute = ProducthuntRouteImport.update({
  id: "/producthunt",
  path: "/producthunt",
  getParentRoute: () => rootRouteImport,
} as any);
const PrivacyRoute = PrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => rootRouteImport,
} as any);
const PricingRoute = PricingRouteImport.update({
  id: "/pricing",
  path: "/pricing",
  getParentRoute: () => rootRouteImport,
} as any);
const PostsRoute = PostsRouteImport.update({
  id: "/posts",
  path: "/posts",
  getParentRoute: () => rootRouteImport,
} as any);
const IosRoute = IosRouteImport.update({
  id: "/ios",
  path: "/ios",
  getParentRoute: () => rootRouteImport,
} as any);
const ImportsRoute = ImportsRouteImport.update({
  id: "/imports",
  path: "/imports",
  getParentRoute: () => rootRouteImport,
} as any);
const HelpRoute = HelpRouteImport.update({
  id: "/help",
  path: "/help",
  getParentRoute: () => rootRouteImport,
} as any);
const GoodbyeRoute = GoodbyeRouteImport.update({
  id: "/goodbye",
  path: "/goodbye",
  getParentRoute: () => rootRouteImport,
} as any);
const ExtensionsRoute = ExtensionsRouteImport.update({
  id: "/extensions",
  path: "/extensions",
  getParentRoute: () => rootRouteImport,
} as any);
const ExportsRoute = ExportsRouteImport.update({
  id: "/exports",
  path: "/exports",
  getParentRoute: () => rootRouteImport,
} as any);
const ExploreRoute = ExploreRouteImport.update({
  id: "/explore",
  path: "/explore",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsRoute = DocsRouteImport.update({
  id: "/docs",
  path: "/docs",
  getParentRoute: () => rootRouteImport,
} as any);
const ContactRoute = ContactRouteImport.update({
  id: "/contact",
  path: "/contact",
  getParentRoute: () => rootRouteImport,
} as any);
const ChangelogRoute = ChangelogRouteImport.update({
  id: "/changelog",
  path: "/changelog",
  getParentRoute: () => rootRouteImport,
} as any);
const BillingRoute = BillingRouteImport.update({
  id: "/billing",
  path: "/billing",
  getParentRoute: () => rootRouteImport,
} as any);
const AppRoute = AppRouteImport.update({
  id: "/app",
  path: "/app",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any);
const AccountRoute = AccountRouteImport.update({
  id: "/account",
  path: "/account",
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any);
const SplatRoute = SplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const UpgradeSuccessRoute = UpgradeSuccessRouteImport.update({
  id: "/success",
  path: "/success",
  getParentRoute: () => UpgradeRoute,
} as any);
const UpgradeNewPricingRoute = UpgradeNewPricingRouteImport.update({
  id: "/new-pricing",
  path: "/new-pricing",
  getParentRoute: () => UpgradeRoute,
} as any);
const UnsubscribeUserIdRoute = UnsubscribeUserIdRouteImport.update({
  id: "/unsubscribe/$userId",
  path: "/unsubscribe/$userId",
  getParentRoute: () => rootRouteImport,
} as any);
const USlugRoute = USlugRouteImport.update({
  id: "/u/$slug",
  path: "/u/$slug",
  getParentRoute: () => rootRouteImport,
} as any);
const ToolsYoutubeMetadataRoute = ToolsYoutubeMetadataRouteImport.update({
  id: "/youtube-metadata",
  path: "/youtube-metadata",
  getParentRoute: () => ToolsRoute,
} as any);
const ToolsOgImagesRoute = ToolsOgImagesRouteImport.update({
  id: "/og-images",
  path: "/og-images",
  getParentRoute: () => ToolsRoute,
} as any);
const ToolsExtractMetadataRoute = ToolsExtractMetadataRouteImport.update({
  id: "/extract-metadata",
  path: "/extract-metadata",
  getParentRoute: () => ToolsRoute,
} as any);
const ToolsExtractFaviconsRoute = ToolsExtractFaviconsRouteImport.update({
  id: "/extract-favicons",
  path: "/extract-favicons",
  getParentRoute: () => ToolsRoute,
} as any);
const ToolsExtractContentRoute = ToolsExtractContentRouteImport.update({
  id: "/extract-content",
  path: "/extract-content",
  getParentRoute: () => ToolsRoute,
} as any);
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: "/$slug",
  path: "/$slug",
  getParentRoute: () => PostsRoute,
} as any);
const PBookmarkIdRoute = PBookmarkIdRouteImport.update({
  id: "/p/$bookmarkId",
  path: "/p/$bookmarkId",
  getParentRoute: () => rootRouteImport,
} as any);
const LandingHeader2Route = LandingHeader2RouteImport.update({
  id: "/landing/header-2",
  path: "/landing/header-2",
  getParentRoute: () => rootRouteImport,
} as any);
const LandingHeaderRoute = LandingHeaderRouteImport.update({
  id: "/landing/header",
  path: "/landing/header",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: "/$slug",
  path: "/$slug",
  getParentRoute: () => DocsRoute,
} as any);
const ChangelogVersionsRoute = ChangelogVersionsRouteImport.update({
  id: "/versions",
  path: "/versions",
  getParentRoute: () => ChangelogRoute,
} as any);
const AuthMobileLoginRoute = AuthMobileLoginRouteImport.update({
  id: "/auth/mobile-login",
  path: "/auth/mobile-login",
  getParentRoute: () => rootRouteImport,
} as any);
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: "/agents",
  path: "/agents",
  getParentRoute: () => AppRoute,
} as any);
const ApiTagsRoute = ApiTagsRouteImport.update({
  id: "/api/tags",
  path: "/api/tags",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiBugReportRoute = ApiBugReportRouteImport.update({
  id: "/api/bug-report",
  path: "/api/bug-report",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiBookmarksRoute = ApiBookmarksRouteImport.update({
  id: "/api/bookmarks",
  path: "/api/bookmarks",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => AdminRoute,
} as any);
const AdminSendEmailRoute = AdminSendEmailRouteImport.update({
  id: "/send-email",
  path: "/send-email",
  getParentRoute: () => AdminRoute,
} as any);
const AdminConversationsRoute = AdminConversationsRouteImport.update({
  id: "/conversations",
  path: "/conversations",
  getParentRoute: () => AdminRoute,
} as any);
const AccountPublicLinkRoute = AccountPublicLinkRouteImport.update({
  id: "/public-link",
  path: "/public-link",
  getParentRoute: () => AccountRoute,
} as any);
const AccountKeysRoute = AccountKeysRouteImport.update({
  id: "/keys",
  path: "/keys",
  getParentRoute: () => AccountRoute,
} as any);
const PBookmarkIdReadRoute = PBookmarkIdReadRouteImport.update({
  id: "/read",
  path: "/read",
  getParentRoute: () => PBookmarkIdRoute,
} as any);
const AppBBookmarkIdRoute = AppBBookmarkIdRouteImport.update({
  id: "/b/$bookmarkId",
  path: "/b/$bookmarkId",
  getParentRoute: () => AppRoute,
} as any);
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: "/api/webhooks/stripe",
  path: "/api/webhooks/stripe",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: "/api/v1/$",
  path: "/api/v1/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiUserLimitsRoute = ApiUserLimitsRouteImport.update({
  id: "/api/user/limits",
  path: "/api/user/limits",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiMobileCheckoutRoute = ApiMobileCheckoutRouteImport.update({
  id: "/api/mobile/checkout",
  path: "/api/mobile/checkout",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiInsightsSplatRoute = ApiInsightsSplatRouteImport.update({
  id: "/api/insights/$",
  path: "/api/insights/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiBookmarksBookmarkIdRoute = ApiBookmarksBookmarkIdRouteImport.update({
  id: "/$bookmarkId",
  path: "/$bookmarkId",
  getParentRoute: () => ApiBookmarksRoute,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: "/$userId",
  path: "/$userId",
  getParentRoute: () => AdminUsersRoute,
} as any);
const AdminConversationsIdRoute = AdminConversationsIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => AdminConversationsRoute,
} as any);
const ApiBookmarksBookmarkIdUploadScreenshotRoute =
  ApiBookmarksBookmarkIdUploadScreenshotRouteImport.update({
    id: "/upload-screenshot",
    path: "/upload-screenshot",
    getParentRoute: () => ApiBookmarksBookmarkIdRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/about": typeof AboutRoute;
  "/account": typeof AccountRouteWithChildren;
  "/admin": typeof AdminRouteWithChildren;
  "/app": typeof AppRouteWithChildren;
  "/billing": typeof BillingRoute;
  "/changelog": typeof ChangelogRouteWithChildren;
  "/contact": typeof ContactRoute;
  "/docs": typeof DocsRouteWithChildren;
  "/explore": typeof ExploreRoute;
  "/exports": typeof ExportsRoute;
  "/extensions": typeof ExtensionsRoute;
  "/goodbye": typeof GoodbyeRoute;
  "/help": typeof HelpRoute;
  "/imports": typeof ImportsRoute;
  "/ios": typeof IosRoute;
  "/posts": typeof PostsRouteWithChildren;
  "/pricing": typeof PricingRoute;
  "/privacy": typeof PrivacyRoute;
  "/producthunt": typeof ProducthuntRoute;
  "/signin": typeof SigninRoute;
  "/start": typeof StartRoute;
  "/tags": typeof TagsRoute;
  "/terms": typeof TermsRoute;
  "/tools": typeof ToolsRouteWithChildren;
  "/upgrade": typeof UpgradeRouteWithChildren;
  "/variations": typeof VariationsRoute;
  "/verify": typeof VerifyRoute;
  "/account/keys": typeof AccountKeysRoute;
  "/account/public-link": typeof AccountPublicLinkRoute;
  "/admin/conversations": typeof AdminConversationsRouteWithChildren;
  "/admin/send-email": typeof AdminSendEmailRoute;
  "/admin/users": typeof AdminUsersRouteWithChildren;
  "/api/bookmarks": typeof ApiBookmarksRouteWithChildren;
  "/api/bug-report": typeof ApiBugReportRoute;
  "/api/tags": typeof ApiTagsRoute;
  "/app/agents": typeof AppAgentsRoute;
  "/auth/mobile-login": typeof AuthMobileLoginRoute;
  "/changelog/versions": typeof ChangelogVersionsRoute;
  "/docs/$slug": typeof DocsSlugRoute;
  "/landing/header": typeof LandingHeaderRoute;
  "/landing/header-2": typeof LandingHeader2Route;
  "/p/$bookmarkId": typeof PBookmarkIdRouteWithChildren;
  "/posts/$slug": typeof PostsSlugRoute;
  "/tools/extract-content": typeof ToolsExtractContentRoute;
  "/tools/extract-favicons": typeof ToolsExtractFaviconsRoute;
  "/tools/extract-metadata": typeof ToolsExtractMetadataRoute;
  "/tools/og-images": typeof ToolsOgImagesRoute;
  "/tools/youtube-metadata": typeof ToolsYoutubeMetadataRoute;
  "/u/$slug": typeof USlugRoute;
  "/unsubscribe/$userId": typeof UnsubscribeUserIdRoute;
  "/upgrade/new-pricing": typeof UpgradeNewPricingRoute;
  "/upgrade/success": typeof UpgradeSuccessRoute;
  "/admin/conversations/$id": typeof AdminConversationsIdRoute;
  "/admin/users/$userId": typeof AdminUsersUserIdRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/bookmarks/$bookmarkId": typeof ApiBookmarksBookmarkIdRouteWithChildren;
  "/api/insights/$": typeof ApiInsightsSplatRoute;
  "/api/mobile/checkout": typeof ApiMobileCheckoutRoute;
  "/api/user/limits": typeof ApiUserLimitsRoute;
  "/api/v1/$": typeof ApiV1SplatRoute;
  "/api/webhooks/stripe": typeof ApiWebhooksStripeRoute;
  "/app/b/$bookmarkId": typeof AppBBookmarkIdRoute;
  "/p/$bookmarkId/read": typeof PBookmarkIdReadRoute;
  "/api/bookmarks/$bookmarkId/upload-screenshot": typeof ApiBookmarksBookmarkIdUploadScreenshotRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/about": typeof AboutRoute;
  "/account": typeof AccountRouteWithChildren;
  "/admin": typeof AdminRouteWithChildren;
  "/app": typeof AppRouteWithChildren;
  "/billing": typeof BillingRoute;
  "/changelog": typeof ChangelogRouteWithChildren;
  "/contact": typeof ContactRoute;
  "/docs": typeof DocsRouteWithChildren;
  "/explore": typeof ExploreRoute;
  "/exports": typeof ExportsRoute;
  "/extensions": typeof ExtensionsRoute;
  "/goodbye": typeof GoodbyeRoute;
  "/help": typeof HelpRoute;
  "/imports": typeof ImportsRoute;
  "/ios": typeof IosRoute;
  "/posts": typeof PostsRouteWithChildren;
  "/pricing": typeof PricingRoute;
  "/privacy": typeof PrivacyRoute;
  "/producthunt": typeof ProducthuntRoute;
  "/signin": typeof SigninRoute;
  "/start": typeof StartRoute;
  "/tags": typeof TagsRoute;
  "/terms": typeof TermsRoute;
  "/tools": typeof ToolsRouteWithChildren;
  "/upgrade": typeof UpgradeRouteWithChildren;
  "/variations": typeof VariationsRoute;
  "/verify": typeof VerifyRoute;
  "/account/keys": typeof AccountKeysRoute;
  "/account/public-link": typeof AccountPublicLinkRoute;
  "/admin/conversations": typeof AdminConversationsRouteWithChildren;
  "/admin/send-email": typeof AdminSendEmailRoute;
  "/admin/users": typeof AdminUsersRouteWithChildren;
  "/api/bookmarks": typeof ApiBookmarksRouteWithChildren;
  "/api/bug-report": typeof ApiBugReportRoute;
  "/api/tags": typeof ApiTagsRoute;
  "/app/agents": typeof AppAgentsRoute;
  "/auth/mobile-login": typeof AuthMobileLoginRoute;
  "/changelog/versions": typeof ChangelogVersionsRoute;
  "/docs/$slug": typeof DocsSlugRoute;
  "/landing/header": typeof LandingHeaderRoute;
  "/landing/header-2": typeof LandingHeader2Route;
  "/p/$bookmarkId": typeof PBookmarkIdRouteWithChildren;
  "/posts/$slug": typeof PostsSlugRoute;
  "/tools/extract-content": typeof ToolsExtractContentRoute;
  "/tools/extract-favicons": typeof ToolsExtractFaviconsRoute;
  "/tools/extract-metadata": typeof ToolsExtractMetadataRoute;
  "/tools/og-images": typeof ToolsOgImagesRoute;
  "/tools/youtube-metadata": typeof ToolsYoutubeMetadataRoute;
  "/u/$slug": typeof USlugRoute;
  "/unsubscribe/$userId": typeof UnsubscribeUserIdRoute;
  "/upgrade/new-pricing": typeof UpgradeNewPricingRoute;
  "/upgrade/success": typeof UpgradeSuccessRoute;
  "/admin/conversations/$id": typeof AdminConversationsIdRoute;
  "/admin/users/$userId": typeof AdminUsersUserIdRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/bookmarks/$bookmarkId": typeof ApiBookmarksBookmarkIdRouteWithChildren;
  "/api/insights/$": typeof ApiInsightsSplatRoute;
  "/api/mobile/checkout": typeof ApiMobileCheckoutRoute;
  "/api/user/limits": typeof ApiUserLimitsRoute;
  "/api/v1/$": typeof ApiV1SplatRoute;
  "/api/webhooks/stripe": typeof ApiWebhooksStripeRoute;
  "/app/b/$bookmarkId": typeof AppBBookmarkIdRoute;
  "/p/$bookmarkId/read": typeof PBookmarkIdReadRoute;
  "/api/bookmarks/$bookmarkId/upload-screenshot": typeof ApiBookmarksBookmarkIdUploadScreenshotRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/about": typeof AboutRoute;
  "/account": typeof AccountRouteWithChildren;
  "/admin": typeof AdminRouteWithChildren;
  "/app": typeof AppRouteWithChildren;
  "/billing": typeof BillingRoute;
  "/changelog": typeof ChangelogRouteWithChildren;
  "/contact": typeof ContactRoute;
  "/docs": typeof DocsRouteWithChildren;
  "/explore": typeof ExploreRoute;
  "/exports": typeof ExportsRoute;
  "/extensions": typeof ExtensionsRoute;
  "/goodbye": typeof GoodbyeRoute;
  "/help": typeof HelpRoute;
  "/imports": typeof ImportsRoute;
  "/ios": typeof IosRoute;
  "/posts": typeof PostsRouteWithChildren;
  "/pricing": typeof PricingRoute;
  "/privacy": typeof PrivacyRoute;
  "/producthunt": typeof ProducthuntRoute;
  "/signin": typeof SigninRoute;
  "/start": typeof StartRoute;
  "/tags": typeof TagsRoute;
  "/terms": typeof TermsRoute;
  "/tools": typeof ToolsRouteWithChildren;
  "/upgrade": typeof UpgradeRouteWithChildren;
  "/variations": typeof VariationsRoute;
  "/verify": typeof VerifyRoute;
  "/account/keys": typeof AccountKeysRoute;
  "/account/public-link": typeof AccountPublicLinkRoute;
  "/admin/conversations": typeof AdminConversationsRouteWithChildren;
  "/admin/send-email": typeof AdminSendEmailRoute;
  "/admin/users": typeof AdminUsersRouteWithChildren;
  "/api/bookmarks": typeof ApiBookmarksRouteWithChildren;
  "/api/bug-report": typeof ApiBugReportRoute;
  "/api/tags": typeof ApiTagsRoute;
  "/app/agents": typeof AppAgentsRoute;
  "/auth/mobile-login": typeof AuthMobileLoginRoute;
  "/changelog/versions": typeof ChangelogVersionsRoute;
  "/docs/$slug": typeof DocsSlugRoute;
  "/landing/header": typeof LandingHeaderRoute;
  "/landing/header-2": typeof LandingHeader2Route;
  "/p/$bookmarkId": typeof PBookmarkIdRouteWithChildren;
  "/posts/$slug": typeof PostsSlugRoute;
  "/tools/extract-content": typeof ToolsExtractContentRoute;
  "/tools/extract-favicons": typeof ToolsExtractFaviconsRoute;
  "/tools/extract-metadata": typeof ToolsExtractMetadataRoute;
  "/tools/og-images": typeof ToolsOgImagesRoute;
  "/tools/youtube-metadata": typeof ToolsYoutubeMetadataRoute;
  "/u/$slug": typeof USlugRoute;
  "/unsubscribe/$userId": typeof UnsubscribeUserIdRoute;
  "/upgrade/new-pricing": typeof UpgradeNewPricingRoute;
  "/upgrade/success": typeof UpgradeSuccessRoute;
  "/admin/conversations/$id": typeof AdminConversationsIdRoute;
  "/admin/users/$userId": typeof AdminUsersUserIdRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/bookmarks/$bookmarkId": typeof ApiBookmarksBookmarkIdRouteWithChildren;
  "/api/insights/$": typeof ApiInsightsSplatRoute;
  "/api/mobile/checkout": typeof ApiMobileCheckoutRoute;
  "/api/user/limits": typeof ApiUserLimitsRoute;
  "/api/v1/$": typeof ApiV1SplatRoute;
  "/api/webhooks/stripe": typeof ApiWebhooksStripeRoute;
  "/app/b/$bookmarkId": typeof AppBBookmarkIdRoute;
  "/p/$bookmarkId/read": typeof PBookmarkIdReadRoute;
  "/api/bookmarks/$bookmarkId/upload-screenshot": typeof ApiBookmarksBookmarkIdUploadScreenshotRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/$"
    | "/about"
    | "/account"
    | "/admin"
    | "/app"
    | "/billing"
    | "/changelog"
    | "/contact"
    | "/docs"
    | "/explore"
    | "/exports"
    | "/extensions"
    | "/goodbye"
    | "/help"
    | "/imports"
    | "/ios"
    | "/posts"
    | "/pricing"
    | "/privacy"
    | "/producthunt"
    | "/signin"
    | "/start"
    | "/tags"
    | "/terms"
    | "/tools"
    | "/upgrade"
    | "/variations"
    | "/verify"
    | "/account/keys"
    | "/account/public-link"
    | "/admin/conversations"
    | "/admin/send-email"
    | "/admin/users"
    | "/api/bookmarks"
    | "/api/bug-report"
    | "/api/tags"
    | "/app/agents"
    | "/auth/mobile-login"
    | "/changelog/versions"
    | "/docs/$slug"
    | "/landing/header"
    | "/landing/header-2"
    | "/p/$bookmarkId"
    | "/posts/$slug"
    | "/tools/extract-content"
    | "/tools/extract-favicons"
    | "/tools/extract-metadata"
    | "/tools/og-images"
    | "/tools/youtube-metadata"
    | "/u/$slug"
    | "/unsubscribe/$userId"
    | "/upgrade/new-pricing"
    | "/upgrade/success"
    | "/admin/conversations/$id"
    | "/admin/users/$userId"
    | "/api/auth/$"
    | "/api/bookmarks/$bookmarkId"
    | "/api/insights/$"
    | "/api/mobile/checkout"
    | "/api/user/limits"
    | "/api/v1/$"
    | "/api/webhooks/stripe"
    | "/app/b/$bookmarkId"
    | "/p/$bookmarkId/read"
    | "/api/bookmarks/$bookmarkId/upload-screenshot";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/$"
    | "/about"
    | "/account"
    | "/admin"
    | "/app"
    | "/billing"
    | "/changelog"
    | "/contact"
    | "/docs"
    | "/explore"
    | "/exports"
    | "/extensions"
    | "/goodbye"
    | "/help"
    | "/imports"
    | "/ios"
    | "/posts"
    | "/pricing"
    | "/privacy"
    | "/producthunt"
    | "/signin"
    | "/start"
    | "/tags"
    | "/terms"
    | "/tools"
    | "/upgrade"
    | "/variations"
    | "/verify"
    | "/account/keys"
    | "/account/public-link"
    | "/admin/conversations"
    | "/admin/send-email"
    | "/admin/users"
    | "/api/bookmarks"
    | "/api/bug-report"
    | "/api/tags"
    | "/app/agents"
    | "/auth/mobile-login"
    | "/changelog/versions"
    | "/docs/$slug"
    | "/landing/header"
    | "/landing/header-2"
    | "/p/$bookmarkId"
    | "/posts/$slug"
    | "/tools/extract-content"
    | "/tools/extract-favicons"
    | "/tools/extract-metadata"
    | "/tools/og-images"
    | "/tools/youtube-metadata"
    | "/u/$slug"
    | "/unsubscribe/$userId"
    | "/upgrade/new-pricing"
    | "/upgrade/success"
    | "/admin/conversations/$id"
    | "/admin/users/$userId"
    | "/api/auth/$"
    | "/api/bookmarks/$bookmarkId"
    | "/api/insights/$"
    | "/api/mobile/checkout"
    | "/api/user/limits"
    | "/api/v1/$"
    | "/api/webhooks/stripe"
    | "/app/b/$bookmarkId"
    | "/p/$bookmarkId/read"
    | "/api/bookmarks/$bookmarkId/upload-screenshot";
  id:
    | "__root__"
    | "/"
    | "/$"
    | "/about"
    | "/account"
    | "/admin"
    | "/app"
    | "/billing"
    | "/changelog"
    | "/contact"
    | "/docs"
    | "/explore"
    | "/exports"
    | "/extensions"
    | "/goodbye"
    | "/help"
    | "/imports"
    | "/ios"
    | "/posts"
    | "/pricing"
    | "/privacy"
    | "/producthunt"
    | "/signin"
    | "/start"
    | "/tags"
    | "/terms"
    | "/tools"
    | "/upgrade"
    | "/variations"
    | "/verify"
    | "/account/keys"
    | "/account/public-link"
    | "/admin/conversations"
    | "/admin/send-email"
    | "/admin/users"
    | "/api/bookmarks"
    | "/api/bug-report"
    | "/api/tags"
    | "/app/agents"
    | "/auth/mobile-login"
    | "/changelog/versions"
    | "/docs/$slug"
    | "/landing/header"
    | "/landing/header-2"
    | "/p/$bookmarkId"
    | "/posts/$slug"
    | "/tools/extract-content"
    | "/tools/extract-favicons"
    | "/tools/extract-metadata"
    | "/tools/og-images"
    | "/tools/youtube-metadata"
    | "/u/$slug"
    | "/unsubscribe/$userId"
    | "/upgrade/new-pricing"
    | "/upgrade/success"
    | "/admin/conversations/$id"
    | "/admin/users/$userId"
    | "/api/auth/$"
    | "/api/bookmarks/$bookmarkId"
    | "/api/insights/$"
    | "/api/mobile/checkout"
    | "/api/user/limits"
    | "/api/v1/$"
    | "/api/webhooks/stripe"
    | "/app/b/$bookmarkId"
    | "/p/$bookmarkId/read"
    | "/api/bookmarks/$bookmarkId/upload-screenshot";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SplatRoute: typeof SplatRoute;
  AboutRoute: typeof AboutRoute;
  AccountRoute: typeof AccountRouteWithChildren;
  AdminRoute: typeof AdminRouteWithChildren;
  AppRoute: typeof AppRouteWithChildren;
  BillingRoute: typeof BillingRoute;
  ChangelogRoute: typeof ChangelogRouteWithChildren;
  ContactRoute: typeof ContactRoute;
  DocsRoute: typeof DocsRouteWithChildren;
  ExploreRoute: typeof ExploreRoute;
  ExportsRoute: typeof ExportsRoute;
  ExtensionsRoute: typeof ExtensionsRoute;
  GoodbyeRoute: typeof GoodbyeRoute;
  HelpRoute: typeof HelpRoute;
  ImportsRoute: typeof ImportsRoute;
  IosRoute: typeof IosRoute;
  PostsRoute: typeof PostsRouteWithChildren;
  PricingRoute: typeof PricingRoute;
  PrivacyRoute: typeof PrivacyRoute;
  ProducthuntRoute: typeof ProducthuntRoute;
  SigninRoute: typeof SigninRoute;
  StartRoute: typeof StartRoute;
  TagsRoute: typeof TagsRoute;
  TermsRoute: typeof TermsRoute;
  ToolsRoute: typeof ToolsRouteWithChildren;
  UpgradeRoute: typeof UpgradeRouteWithChildren;
  VariationsRoute: typeof VariationsRoute;
  VerifyRoute: typeof VerifyRoute;
  ApiBookmarksRoute: typeof ApiBookmarksRouteWithChildren;
  ApiBugReportRoute: typeof ApiBugReportRoute;
  ApiTagsRoute: typeof ApiTagsRoute;
  AuthMobileLoginRoute: typeof AuthMobileLoginRoute;
  LandingHeaderRoute: typeof LandingHeaderRoute;
  LandingHeader2Route: typeof LandingHeader2Route;
  PBookmarkIdRoute: typeof PBookmarkIdRouteWithChildren;
  USlugRoute: typeof USlugRoute;
  UnsubscribeUserIdRoute: typeof UnsubscribeUserIdRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiInsightsSplatRoute: typeof ApiInsightsSplatRoute;
  ApiMobileCheckoutRoute: typeof ApiMobileCheckoutRoute;
  ApiUserLimitsRoute: typeof ApiUserLimitsRoute;
  ApiV1SplatRoute: typeof ApiV1SplatRoute;
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/verify": {
      id: "/verify";
      path: "/verify";
      fullPath: "/verify";
      preLoaderRoute: typeof VerifyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/variations": {
      id: "/variations";
      path: "/variations";
      fullPath: "/variations";
      preLoaderRoute: typeof VariationsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/upgrade": {
      id: "/upgrade";
      path: "/upgrade";
      fullPath: "/upgrade";
      preLoaderRoute: typeof UpgradeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/tools": {
      id: "/tools";
      path: "/tools";
      fullPath: "/tools";
      preLoaderRoute: typeof ToolsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/terms": {
      id: "/terms";
      path: "/terms";
      fullPath: "/terms";
      preLoaderRoute: typeof TermsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/tags": {
      id: "/tags";
      path: "/tags";
      fullPath: "/tags";
      preLoaderRoute: typeof TagsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/start": {
      id: "/start";
      path: "/start";
      fullPath: "/start";
      preLoaderRoute: typeof StartRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/signin": {
      id: "/signin";
      path: "/signin";
      fullPath: "/signin";
      preLoaderRoute: typeof SigninRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/producthunt": {
      id: "/producthunt";
      path: "/producthunt";
      fullPath: "/producthunt";
      preLoaderRoute: typeof ProducthuntRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/privacy": {
      id: "/privacy";
      path: "/privacy";
      fullPath: "/privacy";
      preLoaderRoute: typeof PrivacyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/pricing": {
      id: "/pricing";
      path: "/pricing";
      fullPath: "/pricing";
      preLoaderRoute: typeof PricingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/posts": {
      id: "/posts";
      path: "/posts";
      fullPath: "/posts";
      preLoaderRoute: typeof PostsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/ios": {
      id: "/ios";
      path: "/ios";
      fullPath: "/ios";
      preLoaderRoute: typeof IosRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/imports": {
      id: "/imports";
      path: "/imports";
      fullPath: "/imports";
      preLoaderRoute: typeof ImportsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/help": {
      id: "/help";
      path: "/help";
      fullPath: "/help";
      preLoaderRoute: typeof HelpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/goodbye": {
      id: "/goodbye";
      path: "/goodbye";
      fullPath: "/goodbye";
      preLoaderRoute: typeof GoodbyeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/extensions": {
      id: "/extensions";
      path: "/extensions";
      fullPath: "/extensions";
      preLoaderRoute: typeof ExtensionsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/exports": {
      id: "/exports";
      path: "/exports";
      fullPath: "/exports";
      preLoaderRoute: typeof ExportsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/explore": {
      id: "/explore";
      path: "/explore";
      fullPath: "/explore";
      preLoaderRoute: typeof ExploreRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs": {
      id: "/docs";
      path: "/docs";
      fullPath: "/docs";
      preLoaderRoute: typeof DocsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/contact": {
      id: "/contact";
      path: "/contact";
      fullPath: "/contact";
      preLoaderRoute: typeof ContactRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/changelog": {
      id: "/changelog";
      path: "/changelog";
      fullPath: "/changelog";
      preLoaderRoute: typeof ChangelogRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/billing": {
      id: "/billing";
      path: "/billing";
      fullPath: "/billing";
      preLoaderRoute: typeof BillingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/app": {
      id: "/app";
      path: "/app";
      fullPath: "/app";
      preLoaderRoute: typeof AppRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin": {
      id: "/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AdminRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/account": {
      id: "/account";
      path: "/account";
      fullPath: "/account";
      preLoaderRoute: typeof AccountRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$": {
      id: "/$";
      path: "/$";
      fullPath: "/$";
      preLoaderRoute: typeof SplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/upgrade/success": {
      id: "/upgrade/success";
      path: "/success";
      fullPath: "/upgrade/success";
      preLoaderRoute: typeof UpgradeSuccessRouteImport;
      parentRoute: typeof UpgradeRoute;
    };
    "/upgrade/new-pricing": {
      id: "/upgrade/new-pricing";
      path: "/new-pricing";
      fullPath: "/upgrade/new-pricing";
      preLoaderRoute: typeof UpgradeNewPricingRouteImport;
      parentRoute: typeof UpgradeRoute;
    };
    "/unsubscribe/$userId": {
      id: "/unsubscribe/$userId";
      path: "/unsubscribe/$userId";
      fullPath: "/unsubscribe/$userId";
      preLoaderRoute: typeof UnsubscribeUserIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/u/$slug": {
      id: "/u/$slug";
      path: "/u/$slug";
      fullPath: "/u/$slug";
      preLoaderRoute: typeof USlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/tools/youtube-metadata": {
      id: "/tools/youtube-metadata";
      path: "/youtube-metadata";
      fullPath: "/tools/youtube-metadata";
      preLoaderRoute: typeof ToolsYoutubeMetadataRouteImport;
      parentRoute: typeof ToolsRoute;
    };
    "/tools/og-images": {
      id: "/tools/og-images";
      path: "/og-images";
      fullPath: "/tools/og-images";
      preLoaderRoute: typeof ToolsOgImagesRouteImport;
      parentRoute: typeof ToolsRoute;
    };
    "/tools/extract-metadata": {
      id: "/tools/extract-metadata";
      path: "/extract-metadata";
      fullPath: "/tools/extract-metadata";
      preLoaderRoute: typeof ToolsExtractMetadataRouteImport;
      parentRoute: typeof ToolsRoute;
    };
    "/tools/extract-favicons": {
      id: "/tools/extract-favicons";
      path: "/extract-favicons";
      fullPath: "/tools/extract-favicons";
      preLoaderRoute: typeof ToolsExtractFaviconsRouteImport;
      parentRoute: typeof ToolsRoute;
    };
    "/tools/extract-content": {
      id: "/tools/extract-content";
      path: "/extract-content";
      fullPath: "/tools/extract-content";
      preLoaderRoute: typeof ToolsExtractContentRouteImport;
      parentRoute: typeof ToolsRoute;
    };
    "/posts/$slug": {
      id: "/posts/$slug";
      path: "/$slug";
      fullPath: "/posts/$slug";
      preLoaderRoute: typeof PostsSlugRouteImport;
      parentRoute: typeof PostsRoute;
    };
    "/p/$bookmarkId": {
      id: "/p/$bookmarkId";
      path: "/p/$bookmarkId";
      fullPath: "/p/$bookmarkId";
      preLoaderRoute: typeof PBookmarkIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/landing/header-2": {
      id: "/landing/header-2";
      path: "/landing/header-2";
      fullPath: "/landing/header-2";
      preLoaderRoute: typeof LandingHeader2RouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/landing/header": {
      id: "/landing/header";
      path: "/landing/header";
      fullPath: "/landing/header";
      preLoaderRoute: typeof LandingHeaderRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/$slug": {
      id: "/docs/$slug";
      path: "/$slug";
      fullPath: "/docs/$slug";
      preLoaderRoute: typeof DocsSlugRouteImport;
      parentRoute: typeof DocsRoute;
    };
    "/changelog/versions": {
      id: "/changelog/versions";
      path: "/versions";
      fullPath: "/changelog/versions";
      preLoaderRoute: typeof ChangelogVersionsRouteImport;
      parentRoute: typeof ChangelogRoute;
    };
    "/auth/mobile-login": {
      id: "/auth/mobile-login";
      path: "/auth/mobile-login";
      fullPath: "/auth/mobile-login";
      preLoaderRoute: typeof AuthMobileLoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/app/agents": {
      id: "/app/agents";
      path: "/agents";
      fullPath: "/app/agents";
      preLoaderRoute: typeof AppAgentsRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/api/tags": {
      id: "/api/tags";
      path: "/api/tags";
      fullPath: "/api/tags";
      preLoaderRoute: typeof ApiTagsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/bug-report": {
      id: "/api/bug-report";
      path: "/api/bug-report";
      fullPath: "/api/bug-report";
      preLoaderRoute: typeof ApiBugReportRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/bookmarks": {
      id: "/api/bookmarks";
      path: "/api/bookmarks";
      fullPath: "/api/bookmarks";
      preLoaderRoute: typeof ApiBookmarksRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin/users": {
      id: "/admin/users";
      path: "/users";
      fullPath: "/admin/users";
      preLoaderRoute: typeof AdminUsersRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/admin/send-email": {
      id: "/admin/send-email";
      path: "/send-email";
      fullPath: "/admin/send-email";
      preLoaderRoute: typeof AdminSendEmailRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/admin/conversations": {
      id: "/admin/conversations";
      path: "/conversations";
      fullPath: "/admin/conversations";
      preLoaderRoute: typeof AdminConversationsRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/account/public-link": {
      id: "/account/public-link";
      path: "/public-link";
      fullPath: "/account/public-link";
      preLoaderRoute: typeof AccountPublicLinkRouteImport;
      parentRoute: typeof AccountRoute;
    };
    "/account/keys": {
      id: "/account/keys";
      path: "/keys";
      fullPath: "/account/keys";
      preLoaderRoute: typeof AccountKeysRouteImport;
      parentRoute: typeof AccountRoute;
    };
    "/p/$bookmarkId/read": {
      id: "/p/$bookmarkId/read";
      path: "/read";
      fullPath: "/p/$bookmarkId/read";
      preLoaderRoute: typeof PBookmarkIdReadRouteImport;
      parentRoute: typeof PBookmarkIdRoute;
    };
    "/app/b/$bookmarkId": {
      id: "/app/b/$bookmarkId";
      path: "/b/$bookmarkId";
      fullPath: "/app/b/$bookmarkId";
      preLoaderRoute: typeof AppBBookmarkIdRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/api/webhooks/stripe": {
      id: "/api/webhooks/stripe";
      path: "/api/webhooks/stripe";
      fullPath: "/api/webhooks/stripe";
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/v1/$": {
      id: "/api/v1/$";
      path: "/api/v1/$";
      fullPath: "/api/v1/$";
      preLoaderRoute: typeof ApiV1SplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/user/limits": {
      id: "/api/user/limits";
      path: "/api/user/limits";
      fullPath: "/api/user/limits";
      preLoaderRoute: typeof ApiUserLimitsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/mobile/checkout": {
      id: "/api/mobile/checkout";
      path: "/api/mobile/checkout";
      fullPath: "/api/mobile/checkout";
      preLoaderRoute: typeof ApiMobileCheckoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/insights/$": {
      id: "/api/insights/$";
      path: "/api/insights/$";
      fullPath: "/api/insights/$";
      preLoaderRoute: typeof ApiInsightsSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/bookmarks/$bookmarkId": {
      id: "/api/bookmarks/$bookmarkId";
      path: "/$bookmarkId";
      fullPath: "/api/bookmarks/$bookmarkId";
      preLoaderRoute: typeof ApiBookmarksBookmarkIdRouteImport;
      parentRoute: typeof ApiBookmarksRoute;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin/users/$userId": {
      id: "/admin/users/$userId";
      path: "/$userId";
      fullPath: "/admin/users/$userId";
      preLoaderRoute: typeof AdminUsersUserIdRouteImport;
      parentRoute: typeof AdminUsersRoute;
    };
    "/admin/conversations/$id": {
      id: "/admin/conversations/$id";
      path: "/$id";
      fullPath: "/admin/conversations/$id";
      preLoaderRoute: typeof AdminConversationsIdRouteImport;
      parentRoute: typeof AdminConversationsRoute;
    };
    "/api/bookmarks/$bookmarkId/upload-screenshot": {
      id: "/api/bookmarks/$bookmarkId/upload-screenshot";
      path: "/upload-screenshot";
      fullPath: "/api/bookmarks/$bookmarkId/upload-screenshot";
      preLoaderRoute: typeof ApiBookmarksBookmarkIdUploadScreenshotRouteImport;
      parentRoute: typeof ApiBookmarksBookmarkIdRoute;
    };
  }
}

interface AccountRouteChildren {
  AccountKeysRoute: typeof AccountKeysRoute;
  AccountPublicLinkRoute: typeof AccountPublicLinkRoute;
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountKeysRoute: AccountKeysRoute,
  AccountPublicLinkRoute: AccountPublicLinkRoute,
};

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren);

interface AdminConversationsRouteChildren {
  AdminConversationsIdRoute: typeof AdminConversationsIdRoute;
}

const AdminConversationsRouteChildren: AdminConversationsRouteChildren = {
  AdminConversationsIdRoute: AdminConversationsIdRoute,
};

const AdminConversationsRouteWithChildren =
  AdminConversationsRoute._addFileChildren(AdminConversationsRouteChildren);

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute;
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
};

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
);

interface AdminRouteChildren {
  AdminConversationsRoute: typeof AdminConversationsRouteWithChildren;
  AdminSendEmailRoute: typeof AdminSendEmailRoute;
  AdminUsersRoute: typeof AdminUsersRouteWithChildren;
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConversationsRoute: AdminConversationsRouteWithChildren,
  AdminSendEmailRoute: AdminSendEmailRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
};

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren);

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRoute;
  AppBBookmarkIdRoute: typeof AppBBookmarkIdRoute;
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRoute,
  AppBBookmarkIdRoute: AppBBookmarkIdRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

interface ChangelogRouteChildren {
  ChangelogVersionsRoute: typeof ChangelogVersionsRoute;
}

const ChangelogRouteChildren: ChangelogRouteChildren = {
  ChangelogVersionsRoute: ChangelogVersionsRoute,
};

const ChangelogRouteWithChildren = ChangelogRoute._addFileChildren(
  ChangelogRouteChildren,
);

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute;
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
};

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren);

interface PostsRouteChildren {
  PostsSlugRoute: typeof PostsSlugRoute;
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsSlugRoute: PostsSlugRoute,
};

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren);

interface ToolsRouteChildren {
  ToolsExtractContentRoute: typeof ToolsExtractContentRoute;
  ToolsExtractFaviconsRoute: typeof ToolsExtractFaviconsRoute;
  ToolsExtractMetadataRoute: typeof ToolsExtractMetadataRoute;
  ToolsOgImagesRoute: typeof ToolsOgImagesRoute;
  ToolsYoutubeMetadataRoute: typeof ToolsYoutubeMetadataRoute;
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsExtractContentRoute: ToolsExtractContentRoute,
  ToolsExtractFaviconsRoute: ToolsExtractFaviconsRoute,
  ToolsExtractMetadataRoute: ToolsExtractMetadataRoute,
  ToolsOgImagesRoute: ToolsOgImagesRoute,
  ToolsYoutubeMetadataRoute: ToolsYoutubeMetadataRoute,
};

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren);

interface UpgradeRouteChildren {
  UpgradeNewPricingRoute: typeof UpgradeNewPricingRoute;
  UpgradeSuccessRoute: typeof UpgradeSuccessRoute;
}

const UpgradeRouteChildren: UpgradeRouteChildren = {
  UpgradeNewPricingRoute: UpgradeNewPricingRoute,
  UpgradeSuccessRoute: UpgradeSuccessRoute,
};

const UpgradeRouteWithChildren =
  UpgradeRoute._addFileChildren(UpgradeRouteChildren);

interface ApiBookmarksBookmarkIdRouteChildren {
  ApiBookmarksBookmarkIdUploadScreenshotRoute: typeof ApiBookmarksBookmarkIdUploadScreenshotRoute;
}

const ApiBookmarksBookmarkIdRouteChildren: ApiBookmarksBookmarkIdRouteChildren =
  {
    ApiBookmarksBookmarkIdUploadScreenshotRoute:
      ApiBookmarksBookmarkIdUploadScreenshotRoute,
  };

const ApiBookmarksBookmarkIdRouteWithChildren =
  ApiBookmarksBookmarkIdRoute._addFileChildren(
    ApiBookmarksBookmarkIdRouteChildren,
  );

interface ApiBookmarksRouteChildren {
  ApiBookmarksBookmarkIdRoute: typeof ApiBookmarksBookmarkIdRouteWithChildren;
}

const ApiBookmarksRouteChildren: ApiBookmarksRouteChildren = {
  ApiBookmarksBookmarkIdRoute: ApiBookmarksBookmarkIdRouteWithChildren,
};

const ApiBookmarksRouteWithChildren = ApiBookmarksRoute._addFileChildren(
  ApiBookmarksRouteChildren,
);

interface PBookmarkIdRouteChildren {
  PBookmarkIdReadRoute: typeof PBookmarkIdReadRoute;
}

const PBookmarkIdRouteChildren: PBookmarkIdRouteChildren = {
  PBookmarkIdReadRoute: PBookmarkIdReadRoute,
};

const PBookmarkIdRouteWithChildren = PBookmarkIdRoute._addFileChildren(
  PBookmarkIdRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  BillingRoute: BillingRoute,
  ChangelogRoute: ChangelogRouteWithChildren,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRouteWithChildren,
  ExploreRoute: ExploreRoute,
  ExportsRoute: ExportsRoute,
  ExtensionsRoute: ExtensionsRoute,
  GoodbyeRoute: GoodbyeRoute,
  HelpRoute: HelpRoute,
  ImportsRoute: ImportsRoute,
  IosRoute: IosRoute,
  PostsRoute: PostsRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProducthuntRoute: ProducthuntRoute,
  SigninRoute: SigninRoute,
  StartRoute: StartRoute,
  TagsRoute: TagsRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRouteWithChildren,
  UpgradeRoute: UpgradeRouteWithChildren,
  VariationsRoute: VariationsRoute,
  VerifyRoute: VerifyRoute,
  ApiBookmarksRoute: ApiBookmarksRouteWithChildren,
  ApiBugReportRoute: ApiBugReportRoute,
  ApiTagsRoute: ApiTagsRoute,
  AuthMobileLoginRoute: AuthMobileLoginRoute,
  LandingHeaderRoute: LandingHeaderRoute,
  LandingHeader2Route: LandingHeader2Route,
  PBookmarkIdRoute: PBookmarkIdRouteWithChildren,
  USlugRoute: USlugRoute,
  UnsubscribeUserIdRoute: UnsubscribeUserIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiInsightsSplatRoute: ApiInsightsSplatRoute,
  ApiMobileCheckoutRoute: ApiMobileCheckoutRoute,
  ApiUserLimitsRoute: ApiUserLimitsRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
